### ISSUE TITLE
[NEW] Why did you choose the zap logger over the built-in echo logger interface?

### ISSUE THREAD

**Issue by dchebakov** [ybkuroki/go-webapp-sample#169]
## Purpose

It seems to me that in services accessing a logger from a container is quite inconvenient, so why did you choose to explicitly pass a container instance to every service?
There might be the following option to do that:
1. Use a native echo Logger
2. Instead of a container instance you could assign a logger to echo.Context and then accessing the logger from it

**Comment by ybkuroki** [comment]
@dchebakov 
Thank you for your valuable opinion.

I'm using a concept called 'Container' for handling some data and functions which wants to share in the overall application in one place. And, I avoid the package dependencies in this repository are complicate.

Those data is set to a container when this application started, and those instance will always be singleton. As you mentioned, I think it's better to aggregate it in `echo.Context` because the concept called this container is same role as `echo.Context`. But, I haven't been able to do it yet because I need to investigate the feasibility.

Regarding logger, I'm using it because a library which I want to try to use was `zap.logger`. This is one of the implementation example.

**Comment by dchebakov** [comment]
Thanks for the quick reply! Do you have an example code repository which shows how one could wrap `echo.Context` (or even `context.Context`) so later in some code parts, you can extract the logger with the bound `request-id` or `user` fields?

**Comment by ybkuroki** [comment]
Thank you for your interest in this repository!
Unfortunately, I don't have a repository like that. But, the similar sample source code is provided in the official site.

- [Extending Context](https://echo.labstack.com/guide/context/)

And I think I would like to include not only `zap.logger` but also the instances of `repository`, `session`, `config` and `env` in `echo.Context`.
Could you please try it using the sample if you would like?
Please let me know if there is any concerns and problems.

**Comment by zuozhehao** [comment]
> Thank you for your interest in this repository! Unfortunately, I don't have a repository like that. But, the similar sample source code is provided in the official site.
> 
> * [Extending Context](https://echo.labstack.com/guide/context/)
> 
> And I think I would like to include not only `zap.logger` but also the instances of `repository`, `session`, `config` and `env` in `echo.Context`. Could you please try it using the sample if you would like? Please let me know if there is any concerns and problems.

It feels more complicated to handle this way, and it will be better to use the concept of container

**Comment by ybkuroki** [comment]
Don't fix it because it will make it more complicated.
